### ISSUE TITLE
Python 3.10 지원

### ISSUE THREAD

**Issue by ZerglingGo** [sharebook-kr/pyupbit#75]
Python 3.10부터 asyncio.Lock() 함수에 loop 파라미터가 삭제되었습니다
이로 인해 현재 사용중인 websockets 패키지 버전과 호환되지 않습니다

```
Process WebSocketManager-1:
Traceback (most recent call last):
  File "C:\Users\zergl\scoop\apps\python\current\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Users\zergl\scoop\apps\python\current\lib\site-packages\pyupbit\websocket_api.py", line 57, in run
    self.__aloop.run_until_complete(self.__connect_socket())
  File "C:\Users\zergl\scoop\apps\python\current\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "C:\Users\zergl\scoop\apps\python\current\lib\site-packages\pyupbit\websocket_api.py", line 43, in __connect_socket
    async with websockets.connect(uri, ping_interval=60) as websocket:
  File "C:\Users\zergl\scoop\apps\python\current\lib\site-packages\websockets\legacy\client.py", line 604, in __aenter__
    return await self
  File "C:\Users\zergl\scoop\apps\python\current\lib\site-packages\websockets\legacy\client.py", line 622, in __await_impl__
    transport, protocol = await self._create_connection()
  File "C:\Users\zergl\scoop\apps\python\current\lib\asyncio\base_events.py", line 1080, in create_connection
    transport, protocol = await self._create_connection_transport(
  File "C:\Users\zergl\scoop\apps\python\current\lib\asyncio\base_events.py", line 1098, in _create_connection_transport
    protocol = protocol_factory()
  File "C:\Users\zergl\scoop\apps\python\current\lib\site-packages\websockets\legacy\client.py", line 160, in __init__
    super().__init__(**kwargs)
  File "C:\Users\zergl\scoop\apps\python\current\lib\site-packages\websockets\legacy\protocol.py", line 154, in __init__
    self._drain_lock = asyncio.Lock(
  File "C:\Users\zergl\scoop\apps\python\current\lib\asyncio\locks.py", line 77, in __init__
    super().__init__(loop=loop)
  File "C:\Users\zergl\scoop\apps\python\current\lib\asyncio\mixins.py", line 17, in __init__
    raise TypeError(
TypeError: As of 3.10, the *loop* parameter was removed from Lock() since it is no longer necessary
```

**Comment by mr-yoo** [comment]
`websockets==8.1` 모듈과 파이썬 3.10의 `asyncio` 간의  `dependency` 문제가 발생하네요.
우선 `websockets`을 업그레이드 해 주시면 동작은 할 겁니다.

`pip install -U websockets`

`websockets==10.3` 버전에서 정상 동작함을 확인했습니다.
